djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from market import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('', views.initial_page, name='initial_page'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from market import views

app_name = 'market'

urlpatterns = [
    path('books/', views.books_information, name='books_information'),
    path('book_listing/', views.book_listing, name='book_listing'),
    path('book_detail/<int:book_id>', views.book_detail, name='book_detail'),
]

market/models.py
from django.db import models
from django.utils.translation import gettext as _


class Author(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name=_('Author Name'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Author')
        verbose_name_plural = _('Authors')


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name=_('Category Name'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class Book(models.Model):
    COVER_TYPES = [
        ('hardback', _('Hardback')),
        ('paperback', _('Paperback')),
        ('special', _('Special')),
    ]

    name = models.CharField(max_length=200, verbose_name=_('Book Name'))
    author_name = models.ForeignKey(Author, on_delete=models.CASCADE, to_field='name', verbose_name=_('Author_Name'))
    page_count = models.IntegerField(default=0, verbose_name=_('Page Count'))
    category = models.ManyToManyField(Category, verbose_name=_('Category'))
    price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name=_('Price'))
    image = models.ImageField(null=True, blank=True, verbose_name=_('Image'))
    description = models.TextField(null=True, blank=True, verbose_name=_('Description'))
    cover_type = models.CharField(max_length=20, choices=COVER_TYPES, verbose_name=_('Cover Type'), default='hardback')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Book')
        verbose_name_plural = _('Books')

market/views.py
import json

from django.core.paginator import Paginator
from django.http import JsonResponse
from market.models import Book, Author, Category
from django.shortcuts import render, get_object_or_404


# from django.utils.translation import gettext


# def initial_page(request):
#     return JsonResponse({'message': 'Welcome to the Bookstore!\n'
#                                     'To get information about a book, use the /book/<book_id> endpoint.\n'
#                                     'To get information about all books, use the /books endpoint.\n'
#                                     'To open admin page go to /admin/ with login: admin, password: admin123'})


def initial_page(request):
    return render(request, 'initial_page.html')


# def book_information(request, book_id):
#     try:
#         book = Book.objects.get(pk=book_id)
#
#         book_info = {
#             'name': book.name,
#             'author_name': book.author_name,
#             'category': book.category,
#             'price': str(book.price),
#             'description': book.description,
#         }
#
#         book_json = json.dumps(book_info)
#         return JsonResponse({'book_info': book_json}, safe=False)
#     except Book.DoesNotExist:
#         return JsonResponse({'error': 'Book not found.'})


def books_information(request):
    books = Book.objects.values_list('name', 'author_name', 'category', 'price')
    books_info = list(books)
    return JsonResponse({'books_info': books_info}, safe=False)


# def book_listing(request):
#     all_books = Book.objects.all()
#
#     paginator = Paginator(all_books, 2)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#
#     return render(request, 'book_listing.html', {'page_obj': page_obj})


def book_listing(request):
    authors = Author.objects.all()
    categories = Category.objects.all()

    author_id = request.GET.get('author')
    category_id = request.GET.get('category')

    all_books = Book.objects.all()

    if author_id:
        all_books = all_books.filter(author_name__id=author_id)

    if category_id:
        all_books = all_books.filter(category__id=category_id)

    paginator = Paginator(all_books, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'book_listing.html',
                  {'page_obj': page_obj,
                   'authors': authors,
                   'categories': categories})


def book_detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    description = book.description
    name = book.name
    author_name = book.author_name
    categories = book.category.all()
    price = book.price
    cover = book.cover_type
    return render(request, 'book_detail.html', {
        'description': description,
        'name': name,
        'author_name': author_name,
        'categories': categories,
        'price': price,
        'cover': cover
    })

market/templates/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Description</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 20px;
            font-size: 28px;
            font-weight: bold;
        }
        p {
            line-height: 1.6;
            margin-bottom: 15px;
            font-size: 18px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Book Description</h1>
        <p><strong>Book Name:</strong> {{ name }}</p>
        <p><strong>Description:</strong> {{ description }}</p>
        <p><strong>Author:</strong> {{ author_name }}</p>
        <p><strong>Category:</strong>
            {% for category in categories %}
                {{ category.name }}
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p><strong>Price:</strong> {{ price }}</p>
        <p><strong>Cover Type:</strong> {{ cover }}</p>
    </div>
</body>
</html>

market/templates/book_listing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Listing</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }

        .book-container {
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 20px;
            margin-bottom: 30px;
            overflow: hidden;
            height: 250px;
        }

        .book-info {
            float: left;
            margin-left: 20px;
        }

        .book-image {
            float: left;
            margin-right: 20px;
        }

        .book-image img {
            max-width: 150px;
            max-height: 200px;
            border-radius: 5px;
        }

        .book-title {
            font-size: 24px;
            margin-bottom: 10px;
            font-weight: bold;
        }

        .book-details {
            font-size: 18px;
            margin-bottom: 5px;
        }

        .pagination {
            margin-top: 20px;
            text-align: center;
        }

        .pagination a {
            display: inline-block;
            padding: 10px 20px;
            margin: 0 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
            color: #333;
            text-decoration: none;
            transition: background-color 0.3s ease;
            font-weight: bold;
            margin-top: -10px;
        }

        .pagination a:hover {
            background-color: #e0e0e0;
        }
    </style>
</head>
<body>
<h1 style="text-align: center;">Book Listing</h1>


<form action="{% url 'market:book_listing' %}" method="get" style="margin-bottom: 20px;">
    <label for="author">Filter by Author:</label>
    <select name="author" id="author">
        <option value="">All Authors</option>
        {% for author in authors %}
            <option value="{{ author.id }}">{{ author.name }}</option>
        {% endfor %}
    </select>

    <label for="category">Filter by Category:</label>
    <select name="category" id="category">
        <option value="">All Categories</option>
        {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>

    <button type="submit">Apply Filters</button>
</form>

{% for book in page_obj %}
    <div class="book-container">
        <div class="book-image">
            {% if book.image %}
                <img src="{{ book.image.url }}" alt="{{ book.title }}">
            {% else %}
                <p>No image available</p>
            {% endif %}
        </div>
        <div class="book-info">
            <h2 class="book-title"><a href="{% url 'market:book_detail' book.id %}">{{ book.name }}</a></h2>
            <p class="book-details">Author: {{ book.author_name }}</p>
            <p class="book-details">Price: {{ book.price }}</p>
            <p class="book-details">Categories:
                {% for category in book.category.all %}
                    {{ category.name }}
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
        </div>
        <div style="clear: both;"></div>
    </div>
{% endfor %}


<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="{% url 'market:book_listing' %}?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% if page_obj.has_next %}
        <a href="{% url 'market:book_listing' %}?page={{ page_obj.next_page_number }}">Next</a>
    {% endif %}
</div>
</body>
</html>

market/templates/initial_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Initial Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
            color: #333;
        }

        .container {
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            font-size: 32px;
            margin-bottom: 20px;
            color: #007bff;
        }

        p {
            font-size: 16px;
            margin-bottom: 10px;
        }

    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to the Bookstore!</h1>
        <p>Welcome to the Bookstore!<br>
           To get information about all books, use the <a href="/market/books">/market/books</a> endpoint.<br>
           To get a list of books, use the <a href="/market/book_listing">/market/book_listing</a> endpoint.<br>
           To get a detailed description of a book, use the <a href="/market/book_detail/{{ book_id }}">/market/book_detail/book_id</a> endpoint.<br>
           To open the admin page, go to <a href="/admin/">Admin Page</a> with login: admin, password: admin123</p>
    </div>
</body>

</html>